[package]
name = "bscc-lang-typescript"
edition.workspace = true
rust-version.workspace = true
version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
bscc-core = { path = "../bscc-core" }
bscc-ast-tier = { path = "../bscc-ast-tier" }
tree-sitter.workspace = true
tree-sitter-typescript.workspace = true
